"""Generate/explain code, write files, and run Jarvis app-builder mode."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.config import get_settings
from app.services import llm
from app.skills.base import SkillBase


def _fallback_app_builder_output(prompt: str) -> str:
    """Deterministic local fallback when remote LLM is unavailable."""
    safe_title = "Jarvis Ecommerce App"
    if "blog" in prompt.lower():
        safe_title = "Jarvis Blog App"
    if "dashboard" in prompt.lower():
        safe_title = "Jarvis Dashboard App"

    return f"""## 🧠 PLAN

- Pages: home, product listing, product detail, cart
- Components: navbar, product card, cart drawer, footer
- Features: App Router structure, API routes under `/app/api`, Vercel-ready defaults

## 📁 FILE STRUCTURE

/app/layout.tsx
/app/page.tsx
/app/products/page.tsx
/app/cart/page.tsx
/app/api/products/route.ts
/components/navbar.tsx
/components/product-card.tsx

## 💻 CODE

### File: /app/layout.tsx
```tsx
import "./globals.css";
import type {{ Metadata }} from "next";

export const metadata: Metadata = {{
  title: "{safe_title}",
  description: "Generated by Jarvis app-builder mode",
}};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="en">
      <body className="bg-slate-950 text-slate-100 min-h-screen">{{children}}</body>
    </html>
  );
}}
```

### File: /app/page.tsx
```tsx
import Link from "next/link";

export default function HomePage() {{
  return (
    <main className="mx-auto max-w-5xl p-6">
      <h1 className="text-3xl font-bold">{"{safe_title}"}</h1>
      <p className="mt-2 text-slate-300">Vercel-ready Next.js App Router starter.</p>
      <div className="mt-6 flex gap-3">
        <Link href="/products" className="rounded bg-cyan-500 px-4 py-2 font-medium text-black">
          Browse Products
        </Link>
        <Link href="/cart" className="rounded border border-slate-700 px-4 py-2">
          Open Cart
        </Link>
      </div>
    </main>
  );
}}
```

### File: /app/products/page.tsx
```tsx
import ProductCard from "@/components/product-card";

const products = [
  {{ id: "1", name: "Wireless Headphones", price: 79 }},
  {{ id: "2", name: "Smart Watch", price: 149 }},
  {{ id: "3", name: "Mechanical Keyboard", price: 99 }},
];

export default function ProductsPage() {{
  return (
    <main className="mx-auto max-w-5xl p-6">
      <h2 className="text-2xl font-semibold">Products</h2>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {{products.map((p) => (
          <ProductCard key={{p.id}} id={{p.id}} name={{p.name}} price={{p.price}} />
        ))}}
      </div>
    </main>
  );
}}
```

### File: /app/cart/page.tsx
```tsx
export default function CartPage() {{
  return (
    <main className="mx-auto max-w-3xl p-6">
      <h2 className="text-2xl font-semibold">Cart</h2>
      <p className="mt-2 text-slate-300">Your cart is ready for checkout flow integration.</p>
    </main>
  );
}}
```

### File: /app/api/products/route.ts
```tsx
import {{ NextResponse }} from "next/server";

export async function GET() {{
  return NextResponse.json([
    {{ id: "1", name: "Wireless Headphones", price: 79 }},
    {{ id: "2", name: "Smart Watch", price: 149 }},
    {{ id: "3", name: "Mechanical Keyboard", price: 99 }},
  ]);
}}
```

### File: /components/navbar.tsx
```tsx
import Link from "next/link";

export default function Navbar() {{
  return (
    <header className="border-b border-slate-800">
      <nav className="mx-auto flex max-w-5xl items-center justify-between p-4">
        <Link href="/" className="font-semibold">Jarvis Store</Link>
        <div className="flex gap-4">
          <Link href="/products">Products</Link>
          <Link href="/cart">Cart</Link>
        </div>
      </nav>
    </header>
  );
}}
```

### File: /components/product-card.tsx
```tsx
import Link from "next/link";

type Props = {{
  id: string;
  name: string;
  price: number;
}};

export default function ProductCard({{ id, name, price }}: Props) {{
  return (
    <article className="rounded-lg border border-slate-800 bg-slate-900 p-4">
      <h3 className="font-medium">{{name}}</h3>
      <p className="mt-2 text-cyan-300">${{price}}</p>
      <Link
        href={{`/products/${{id}}`}}
        className="mt-4 inline-block rounded bg-cyan-500 px-3 py-1 text-sm font-medium text-black"
      >
        View
      </Link>
    </article>
  );
}}
```
"""


class CodeAssistantSkill(SkillBase):
    name = "code_assistant"
    description = (
        "Generate code, explain clipboard code, write files, "
        "and build production Next.js app blueprints."
    )

    @property
    def input_schema(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["generate", "explain_clipboard", "write_file", "app_builder"],
                },
                "prompt": {"type": "string"},
                "code": {"type": "string"},
                "path": {"type": "string"},
                "content": {"type": "string"},
            },
            "required": ["action"],
        }

    async def execute(self, action: str, parameters: dict[str, Any], context: dict[str, Any] | None = None) -> dict[str, Any]:
        settings = get_settings()

        if action == "generate":
            prompt = parameters.get("prompt") or ""
            content = await llm.chat(
                [
                    {
                        "role": "system",
                        "content": (
                            "You are a senior software engineer. "
                            "Write clean, production-quality code and concise notes."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                settings,
                temperature=0.2,
            )
            return {"message": content, "summary_text": content, "code": content}

        if action == "explain_clipboard":
            code = parameters.get("code") or ""
            content = await llm.chat(
                [
                    {
                        "role": "system",
                        "content": "You explain code clearly and practically.",
                    },
                    {"role": "user", "content": f"Explain this code clearly:\n\n{code[:12000]}"},
                ],
                settings,
                temperature=0.2,
            )
            return {"summary_text": content, "message": content}

        if action == "app_builder":
            prompt = (parameters.get("prompt") or "").strip()
            if not prompt:
                return {"message": "Missing prompt for app_builder action."}

            system_prompt = (
                "You are an advanced agentic AI system embedded inside Jarvis.\n"
                "Your role is to act as a full-stack AI application builder that generates complete, "
                "production-ready applications based on user prompts.\n\n"
                "SYSTEM CONTEXT:\n"
                "- Build apps with Next.js App Router\n"
                "- Target Vercel deployment\n"
                "- Use Tailwind CSS\n"
                "- Backend APIs under /app/api\n\n"
                "RULES:\n"
                "- Deterministic and clean output\n"
                "- Avoid unnecessary explanations\n"
                "- Focus on working code\n"
                "- Use functional React components\n"
                "- Use modern Next.js patterns only\n"
                "- Keep imports valid\n"
                "- If user asks to modify existing app: only update relevant files\n\n"
                "STRICT OUTPUT FORMAT:\n"
                "## 🧠 PLAN\n"
                "- Pages\n"
                "- Components\n"
                "- Features\n\n"
                "## 📁 FILE STRUCTURE\n"
                "/app/page.tsx\n"
                "/app/layout.tsx\n"
                "/app/api/...\n"
                "/components/...\n\n"
                "## 💻 CODE\n"
                "For each file:\n"
                "### File: /path/to/file\n"
                "```tsx\n"
                "// code\n"
                "```\n"
            )

            try:
                messages = [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ]
                if settings.bedrock_enabled:
                    built = await llm.bedrock_chat(
                        messages,
                        settings,
                        temperature=0.1,
                        max_tokens=6000,
                    )
                else:
                    # Keep the rest of Jarvis on NVIDIA NIM/Ollama. Only app_builder can use Bedrock when enabled.
                    built = await llm.chat(
                        messages,
                        settings,
                        temperature=0.1,
                        force_smart=True,
                    )
            except Exception:
                built = _fallback_app_builder_output(prompt)

            # Enforce strict Jarvis app-builder format even if remote model drifts.
            if (
                "## 🧠 PLAN" not in built
                or "## 📁 FILE STRUCTURE" not in built
                or "## 💻 CODE" not in built
            ):
                built = _fallback_app_builder_output(prompt)
            return {
                "message": built,
                "summary_text": built,
                "code": built,
                "skill_type": "app_builder",
            }

        if action == "write_file":
            path = Path(parameters["path"]).expanduser().resolve()
            content = parameters.get("content") or ""
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            return {"message": f"Wrote {path}"}

        return {"message": f"Unknown action {action}"}
